<a href="https://colab.research.google.com/github/ravbuilds/explore-datascience/blob/main/DataManipulation_Numpy%26Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy Arrays
Here we will cover following topics
**Array Attributes**
**Indexing, Slicing, Reshaping, Joining and Splitting.**

In [1]:
import numpy as np

In [2]:
np.random.seed(10)

In [3]:
x1 = np.random.randint(10, size=6) #1-D array
x2 = np.random.randint(10, size=(3,4)) #2-D array
x3 = np.random.randint(10, size=(2, 3, 5)) #3-D array

In [4]:
print(f"1-D array: {x1}")
print(f"2-D array: {x2}")
print(f"3-D array: {x3}")

1-D array: [9 4 0 1 9 0]
2-D array: [[1 8 9 0]
 [8 6 4 3]
 [0 4 6 8]]
3-D array: [[[1 8 4 1 3]
  [6 5 3 9 6]
  [9 1 9 4 2]]

 [[6 7 8 8 9]
  [2 0 6 7 8]
  [1 7 1 4 0]]]

In [5]:
print("Number of dimensions, Shape and Size")
print(f"1-D array: nDim: {x1.ndim}, shape: {x1.shape}, size: {x1.size}\n")
print(f"2-D array: nDim: {x2.ndim}, shape: {x2.shape}, size: {x2.size}\n")
print(f"3-D array: nDim: {x3.ndim}, shape: {x3.shape}, size: {x3.size}\n")

Number of dimensions, Shape and Size
1-D array: nDim: 1, shape: (6,), size: 6

2-D array: nDim: 2, shape: (3, 4), size: 12

3-D array: nDim: 3, shape: (2, 3, 5), size: 30

In [9]:
print("Without Copy. Simple Assignment to create sub arrays \n")
x2_sub = x2[:2, :2]
print(f"Original: {x2}")
print(print(f"Subarray: {x2_sub}"))
print("\nModify the sub array\n")
x2_sub[0, 0] = 100
print(f"Original: {x2}")
print(f"Subarray: {x2_sub}")
print("Changing the subarray changes the original as well.\n\n")

Without Copy. Simple Assignment to create sub arrays

Original: [[100   8   9   0]
 [  8   6   4   3]
 [  0   4   6   8]]
Subarray: [[100   8]
 [  8   6]]
None

Modify the sub array

Original: [[100   8   9   0]
 [  8   6   4   3]
 [  0   4   6   8]]
Subarray: [[100   8]
 [  8   6]]
Changing the subarray changes the original as well.

In [11]:
print("Using Copy \n")
x2_sub_copy = x2[:2, :2].copy()
print(f"Original: {x2}")
print(print(f"Subarray: {x2_sub_copy}"))
print("\nModify the sub array\n")
x2_sub_copy[0, 0] = 200
print(f"Original: {x2}")
print(f"Subarray: {x2_sub_copy}")
print("Changing the subarray does changes the original as well.\n\n")

Using Copy

Original: [[100   8   9   0]
 [  8   6   4   3]
 [  0   4   6   8]]
Subarray: [[100   8]
 [  8   6]]
None

Modify the sub array

Original: [[100   8   9   0]
 [  8   6   4   3]
 [  0   4   6   8]]
Subarray: [[200   8]
 [  8   6]]
Changing the subarray does changes the original as well.

### RESHAPE
The most flexible way of doing this is with the `reshape()` method. The reshape method will use a no-copy view of the initial array.

In [13]:
grid = np.arange(1, 10).reshape(3, 3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### UNIVERSAL FUNCTIONS (UFUNC)
Computation on NumPy arrays can be very fast, or it can be very slow. The key to
making it fast is to use vectorized operations, generally implemented through Num‐Py’s universal functions (ufuncs).
NumPy provides a convenient interface into statically typed, compiled routine. This is known as a vectorized operation.
You can accomplish this by simply performing an operation on the array, which will then be applied to each element.

In [18]:
# Using Python's simple loop
def compute_reciprocals(values):
  result = np.empty(len(values))

  for i in range(len(values)):
    result[i] = 1.0/values[i]
  return result

In [19]:
print('Processing array of size 1M using Python loop')
big_arr = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_arr)

Processing array of size 1M using Python loop
2.24 s ± 498 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [20]:
print('Processing array using NumPy.')
%timeit (1.0/big_arr)

Processing array using NumPy.
2.1 ms ± 311 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

## Pandas
Pandas is a newer package built on top of NumPy, and provides an
efficient implementation of a DataFrame. DataFrames are essentially multidimensional arrays with attached row and column labels, and often with heterogeneous types and/or missing data.

In [21]:
import pandas as pd
pd.__version__

'2.2.2'

### PANDA'S OBJECTS
The three fundamental Pandas data structures:
* **Series**: A Pandas Series is a 1D array of indexed data. It can be created from a list or array using `pd.Series()`
* **DataFrame**: DataFrame is a 2D array and can be thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary.
* **Index**: It can be thought of either as an immutable array or as an
ordered set.

#### SERIES
Series object is basically interchangeable with a one-dimensional NumPy array. The essential difference is the presence of the index: <br/>
While the NumPy array has an *implicitly* defined integer index used
to access the values, the Pandas Series has an *explicitly* defined index associated with the values.

In [26]:
series = pd.Series(['AAPL', 'ORCL', 'GOOG', 'MSFT', 'IBM'])
series

0    AAPL
1    ORCL
2    GOOG
3    MSFT
4     IBM
dtype: object

In [27]:
print(f"Series value: {series.values}")
print(f"Series index: {series.index}")

Series value: ['AAPL' 'ORCL' 'GOOG' 'MSFT' 'IBM']
Series index: RangeIndex(start=0, stop=5, step=1)

In [30]:
print('Using explicity Index')
series_1 = pd.Series(['AAPL', 'ORCL', 'GOOG', 'MSFT', 'IBM'], index=[2,4,6,8,10])
print(series_1)
print('Using explicity Non Integer Index')
series_2 = pd.Series(['AAPL', 'ORCL', 'GOOG', 'MSFT', 'IBM'], index=['a','b','c','d','e'])
print(series_2)

Using explicity Index
2     AAPL
4     ORCL
6     GOOG
8     MSFT
10     IBM
dtype: object
Using explicity Non Integer Index
a    AAPL
b    ORCL
c    GOOG
d    MSFT
e     IBM
dtype: object

In [31]:
print(f"Series value: {series_2.values}")
print(f"Series index: {series_2.index}")

Series value: ['AAPL' 'ORCL' 'GOOG' 'MSFT' 'IBM']
Series index: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

**SERIES AS SPECIALIZED DICTIONARY**:<br/>
In this way, you can think of a Pandas Series a bit like a specialization of a Python dictionary. A dictionary is a structure that maps arbitrary keys to a set of arbitrary values, and a Series is a structure that maps typed keys to a set of typed values.

In [34]:
population_dict = {
    'California': 38332521,
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135
  }

print(f"Python dictionary: {population_dict}")

Python dictionary: {'California': 38332521, 'Texas': 26448193, 'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135}

In [36]:
population_series = pd.Series(population_dict)
print(f"Series as dictionary: \n{population_series}")

Series as dictionary:
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

#### DATAFRAME
DataFrame maps a column name to a Series of column data.

In [38]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}
area_series = pd.Series(area_dict)

In [40]:
print(f"Population Series: \n{population_series}\n")
print(f"Area Series: \n{area_series}\n")

Population Series:
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

Area Series:
California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [41]:
states_data = pd.DataFrame({"population": population_series, "area": area_series})
print("States DataFrame")
states_data

States DataFrame

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

**DataFrame as specialized dictionary**:</br>
Where a dictionary maps a key to a value, a DataFrame maps a column name to a Series of column data.

In [43]:
print(f"Area:\n{states_data['area']}")

Area:
California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

**CREATE DATAFRAME**:<br/>
1. **From single series object**: A DataFrame is a collection of Series objects, and a single column DataFrame can be constructed from a single Series.
2. **From a list of dicts**: Even if some keys in the dictionary are missing, Pandas will fill them in with NaN (i.e.,“not a number”) values.
3. **From a dictionary of Series objects**: A DataFrame can be constructed
from a dictionary of Series objects as well.
4. **From a two-dimensional NumPy array**: Given a two-dimensional array of data, we can create a DataFrame with any specified column and index names. If omitted, an integer index will be used for each.
5. **From a NumPy structured array**

In [51]:
single_df = pd.DataFrame(area_series, columns=['Area'])
print(f"Single Series DF:\n{single_df}")

dict_df = pd.DataFrame([{'Apple': 'APPL', 'Google': 'GOOG', 'Microsoft': 'MSFT', 'IBM': 'IBM'}])
print(f"Dictionary DF:\n{dict_df}")

Single Series DF:
              Area
California  423967
Texas       695662
New York    141297
Florida     170312
Illinois    149995
Dictionary DF:
  Apple Google Microsoft  IBM
0  APPL   GOOG      MSFT  IBM

### INDEX
This Index object is an interesting
structure in itself, and it can be thought of either as an immutable array or as an ordered set (technically a multiset, as Index objects may contain repeated values).

In [52]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [55]:
ind = pd.Index([2, 3, 5, 7, 11], dtype='int8')
ind

Index([2, 3, 5, 7, 11], dtype='int8')

### DATA INDEXING & SELECTION

**DATA SELECTION IN SERIES**</br>
Think of Series acting in many ways like a **one dimensional NumPy array**, and in many ways like a standard **Python dictionary**.
1. **Series as dictionary**: Like a dictionary, the Series object provides a mapping from a collection of keys to a collection of values.
2. **Indexers: loc, iloc, and ix**: These slicing and indexing conventions can be a source of confusion.
For example, if your Series has an explicit integer index, an indexing operation such as data[1] will use the explicit indices, while a slicing operation like data[1:3] will use the implicit Python-style index.<br/>
**To avoid this confusion Pandas provides some special indexer attributes that explicitly expose certain indexing schemes.** </br>
* **loc**: allows indexing and slicing that always references the *explicit* index.
* **iloc**: allows indexing and slicing that always reference the *implicit* index

In [61]:
print('Series as dictionary.')
print(f"Apple ticker: {series[0]}")
print(f"Apple ticker: {series_2['a']}")

Series as dictionary.
Apple ticker: AAPL
Apple ticker: AAPL

In [63]:
series_1

2     AAPL
4     ORCL
6     GOOG
8     MSFT
10     IBM
dtype: object

In [67]:
print("Explicit Index v/s Implicit Index\n")
print(f"Explicit Index: {series_1[2]}")
print(f"Implicity Index:\n{series_1[1:3]}")

Explicit Index v/s Implicit Index

Explicit Index: AAPL
Implicity Index:
4    ORCL
6    GOOG
dtype: object

In [70]:
print("Using loc and iloc\n")
print(f"loc: {series_1[2]}")
print(f"iloc:{series_1[0:2]}")

Using loc and iloc

loc: AAPL
iloc:2    AAPL
4    ORCL
dtype: object

**DATA SELECTION IN DATAFRAME**
DataFrame acts in many ways like a two-dimensional or structured array,
and in other ways like a dictionary of Series structures sharing the same index.

* **DataFrame as a dictionary**: The individual Series that make up the columns of the DataFrame can be accessed via dictionary-style indexing of the column name: `df['column_name'] or df.column_name`.
* **DataFrame as a 2D array **: Using the same loc, iloc, idx and other Python and Numpy operations

In [72]:
states_data

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [74]:
print(f"Area only:\n{states_data.area}")

Area only:
California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [87]:
print(f"Florida's Area using iloc and dictionary access : {states_data['area'].iloc[3]}")
print(f"Florida's Area using ix : {states_data['area'].iloc[3]}")

Florida's Area using iloc and dictionary access : 170312
Florida's Area using ix : 170312

In [83]:
# Using DF as Two Dimensional array
print(f"DF values: {states_data.values}")

DF values: [[38332521   423967]
 [26448193   695662]
 [19651127   141297]
 [19552860   170312]
 [12882135   149995]]

In [85]:
# Transpose
print("Transpose DataFrame\n")
states_data.T

Transpose DataFrame

            California     Texas  New York   Florida  Illinois
population    38332521  26448193  19651127  19552860  12882135
area            423967    695662    141297    170312    149995

### DATA OPERATIONS IN PANDAS
Pandas inherits much of the functionality from NumPy, and the ufuncs are key to this.
Pandas includes a couple useful twists:
1. For unary operations like negation and trigonometric functions, these ufuncs will preserve index and column labels in the output.
2. For binary operations such as addition and multiplication, Pandas will
automatically align indices when passing the objects to the ufunc.

In [88]:
rng = np.random.RandomState(42)
rng

RandomState(MT19937) at 0x7D63D30B5140

In [89]:
series_random = pd.Series(rng.randint(0, 10, 4))
series_random

0    6
1    3
2    7
3    4
dtype: int64

In [90]:
test_df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['A', 'B', 'C', 'D'])
test_df

   A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [94]:
print('Apply Numpy Operations on Pandas Series and DataFrame')
print("\nApply np.exp on series:")
print(np.exp(series_random))
print("\n np.square on dataframe")
print(np.square(test_df))

Apply Numpy Operations on Pandas Series and DataFrame

Apply np.exp on series:
0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

 np.square on dataframe
    A   B   C   D
0  36  81   4  36
1  49  16   9  49
2  49   4  25  16

**INDEX ALIGNMENT - IN SERIES**<br/>
For binary operations on two Series or DataFrame objects, Pandas will align indices in the process of performing the operation. This is very convenient when you are working with **incomplete data or imbalanced dataset.**

In [102]:
print("\nIndex Alignment in Series.\n")
print('Two series for area and population of US states.')
area = pd.Series({'Alaska': 1723377, 'Texas': 695662, 'California': 423967}, name='area')
population = pd.Series({'California': 38332521,'Texas': 695662, 'New York': 19651127}, name='population')
print(f"Area:\n{area}\n")
print(f"Population:\n{population}")

Index Alignment in Series.

Two series for area and population of US states.
Area:
Alaska        1723377
Texas          695662
California     423967
Name: area, dtype: int64

Population:
California    38332521
Texas           695662
New York      19651127
Name: population, dtype: int64

In [101]:
print(f"Population Density:\n{population/area}")

Population Density:
Alaska              NaN
California    90.413926
New York            NaN
Texas          1.000000
dtype: float64

**INDEX ALIGNMENT - IN DATAFRAME**<br/>

In [106]:
print("\nIndex Alignment in DataFrame.\n")
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))
print(f"DataFrame A:\n{A}")
print(f"DataFrame B:\n{B}")
print(f"\nA+B:\n{A+B}")

Index Alignment in DataFrame.

DataFrame A:
    A   B
0   8   1
1  19  14
DataFrame B:
   B  A  C
0  6  7  2
1  0  3  1
2  7  3  1

A+B:
      A     B   C
0  15.0   7.0 NaN
1  22.0  14.0 NaN
2   NaN   NaN NaN

### HANDLING MISSING DATA
**Trade-Offs in Missing Data**<br/>
Two Strategies:
1. **Masking Approach**: The mask might be an entirely separate Boolean array, or it may involve appropriation of one bit in the data representation to locally indicate the null status of a value. **This adds Overhead in storage and computation.**
2. **Sentinel Approach**: the sentinel value could be some data-specific convention, such as indicating a missing integer value with `–9999 or some rare bit pattern`. **May require extra logic in CPU/GPU arithmetic.**

* **None:Pythanic missing data**: The first sentinel value used by Pandas is None, a Python singleton object that is often used for missing data in Python code. Because None is a Python object, it cannot be used in any arbitrary NumPy/Pandas array, but only in arrays with data type 'object' (i.e., arrays of Python objects).
* **NaN: Missing numerical data**: special floating-point value recognized by all systems that use the standard IEEE floating-point representation. Regardless of the operation, the result of arithmetic with NaN
will be another NaN

In [108]:
# None and NaN
print("None and NaN\n")
vals_None = np.array([1, None, 3, 4])
vals_None

None and NaN

array([1, None, 3, 4], dtype=object)

In [110]:
vals_NaN = np.array([1, np.nan, 3, 4])

vals_NaN

array([ 1., nan,  3.,  4.])

**OPERATION ON NULL VALUES**
Pandas treats None and NaN as essentially interchangeable for indicating
missing or null values.
Here are some methods for detecting, removing and replacing null values in Pandas.
* isnull() -> Generate a Boolean mask indicating missing values
* notnull() -> Opposite of isnull().
* dropna() -> Return filtered version of data
* fillna() -> return a copy of data with missing values filled or imputed.

In [120]:
states_data_imbalanced = pd.DataFrame([area, population]).T
states_data_imbalanced['code']=['AK', 'TX', 'CA', 'NY']
states_data_imbalanced

                 area  population code
Alaska      1723377.0         NaN   AK
Texas        695662.0    695662.0   TX
California   423967.0  38332521.0   CA
New York          NaN  19651127.0   NY

In [121]:
print("Operations on Null values or Missing values.\n")
print(f"isNull:\n{states_data_imbalanced.isnull()}")

Operations on Null values or Missing values.

isNull:
             area  population   code
Alaska      False        True  False
Texas       False       False  False
California  False       False  False
New York     True       False  False

In [122]:
print(f"notNull:\n{states_data_imbalanced.notnull()}")

notNull:
             area  population  code
Alaska       True       False  True
Texas        True        True  True
California   True        True  True
New York    False        True  True

In [125]:
print("Drop Null Values")
print("We cannot drop single values from DataFrame. We can only drop full rows or full columns.\n")

Drop Null Values
We cannot drop single values from DataFrame. We can only drop full rows or full columns.

In [126]:
print("Drop Rows (default)\n")
states_data_imbalanced.dropna()

Drop Rows (default)

                area  population code
Texas       695662.0    695662.0   TX
California  423967.0  38332521.0   CA

In [127]:
print("Drop Columns (axis=1)\n")
states_data_imbalanced.dropna(axis=1)

Drop Columns (axis=1)

           code
Alaska       AK
Texas        TX
California   CA
New York     NY

In [128]:
print("Drop Columns (axis=1) if all values are null\n")
states_data_imbalanced.dropna(axis=1, how='all')

Drop Columns (axis=1) if all values are null

                 area  population code
Alaska      1723377.0         NaN   AK
Texas        695662.0    695662.0   TX
California   423967.0  38332521.0   CA
New York          NaN  19651127.0   NY

In [129]:
print("Fill missing values using various techniques.\n")
print("1. fillna(0)")
states_data_imbalanced.fillna(0)

Fill missing values.

                 area  population code
Alaska      1723377.0         0.0   AK
Texas        695662.0    695662.0   TX
California   423967.0  38332521.0   CA
New York          0.0  19651127.0   NY

In [131]:
print("1. ffill. forward-fill to propagate the previous value forward")
states_data_imbalanced.ffill()

1. ffill. forward-fill to propagate the previous value forward

                 area  population code
Alaska      1723377.0         NaN   AK
Texas        695662.0    695662.0   TX
California   423967.0  38332521.0   CA
New York     423967.0  19651127.0   NY

In [132]:
print("1. bfill. backward-fill to propagate the next value backward")
states_data_imbalanced.bfill()

1. bfill. backward-fill to propagate the next value backward

                 area  population code
Alaska      1723377.0    695662.0   AK
Texas        695662.0    695662.0   TX
California   423967.0  38332521.0   CA
New York          NaN  19651127.0   NY

### Combining Datasets: Concat and Append
These operations can involve anything from very straightforward concatenation
of two different datasets, to more complicated database-style joins and merges
that correctly handle any overlaps between the datasets. Series and DataFrames are built with this type of operation in mind, and Pandas includes functions and methods that make this sort of data wrangling fast and straightforward.

In [140]:
companies = [
    {'Ticker': 'AAPL', 'Company': 'Apple'},
    {'Ticker': 'GOOG', 'Company': 'Google'},
    {'Ticker': 'MSFT', 'Company': 'Microsoft'},
    {'Ticker': 'NVDA', 'Company': 'NVidia'},
    {'Ticker': 'AMZN', 'Company': 'Amazon'}
]
companies_data = pd.DataFrame(companies, columns=['Ticker', 'Company'])
companies_data

  Ticker    Company
0   AAPL      Apple
1   GOOG     Google
2   MSFT  Microsoft
3   NVDA     NVidia
4   AMZN     Amazon

In [141]:
companies_stock = pd.DataFrame([
    {'Ticker': 'AAPL', 'Price': 249.80},
    {'Ticker': 'GOOG', 'Price': 302.58},
    {'Ticker': 'MSFT', 'Price': 383.65},
    {'Ticker': 'NVDA', 'Price': 174.90},
    {'Ticker': 'AMZN', 'Price': 207.10}
])
companies_stock

  Ticker   Price
0   AAPL  249.80
1   GOOG  302.58
2   MSFT  383.65
3   NVDA  174.90
4   AMZN  207.10

**Concat operation**

In [146]:
print("Simple Concatenation")
combined = pd.concat([companies_data, companies_stock], axis=1)
combined

Simple Concatenation

  Ticker    Company Ticker   Price
0   AAPL      Apple   AAPL  249.80
1   GOOG     Google   GOOG  302.58
2   MSFT  Microsoft   MSFT  383.65
3   NVDA     NVidia   NVDA  174.90
4   AMZN     Amazon   AMZN  207.10

**Merge Operation**

In [150]:
print("Merge Dataframes")
merged = pd.merge(companies_data, companies_stock, on='Ticker')
merged

Merge Dataframes

  Ticker    Company   Price
0   AAPL      Apple  249.80
1   GOOG     Google  302.58
2   MSFT  Microsoft  383.65
3   NVDA     NVidia  174.90
4   AMZN     Amazon  207.10

### Aggregation & Grouping
An essential piece of analysis of large data is efficient summarization: computing aggregations like sum(), mean(), median(), min(), and max(), in which a single number gives insight into the nature of a potentially large dataset.

In [157]:
print("Describe DataFrame\n")
merged.describe()

Describe DataFrame

            Price
count    5.000000
mean   263.606000
std     82.434554
min    174.900000
25%    207.100000
50%    249.800000
75%    302.580000
max    383.650000

In [163]:
import pandas as pd

def parse_market_cap(market_cap_str):
    if isinstance(market_cap_str, (int, float)):
        return float(market_cap_str)
    market_cap_str = market_cap_str.strip().upper()
    if market_cap_str.endswith('T'):
        return float(market_cap_str[:-1]) * 1e12
    elif market_cap_str.endswith('B'):
        return float(market_cap_str[:-1]) * 1e9
    elif market_cap_str.endswith('M'):
        return float(market_cap_str[:-1]) * 1e6
    return float(market_cap_str)

sp500_companies = [
    # Technology
    {'Ticker': 'AAPL', 'Name': 'Apple Inc.', 'Stock_Price': 178.25, 'Sector': 'Technology', 'Market_Cap': 2.8e12, 'Volume': 52000000, 'Beta': 1.29, 'PE_Ratio': 29.5, 'Year_Founded': 1976, 'CEO': 'Tim Cook'},
    {'Ticker': 'MSFT', 'Name': 'Microsoft Corporation', 'Stock_Price': 378.91, 'Sector': 'Technology', 'Market_Cap': 2.82e12, 'Volume': 22000000, 'Beta': 0.90, 'PE_Ratio': 35.2, 'Year_Founded': 1975, 'CEO': 'Satya Nadella'},
    {'Ticker': 'GOOGL', 'Name': 'Alphabet Inc.', 'Stock_Price': 141.80, 'Sector': 'Technology', 'Market_Cap': 1.77e12, 'Volume': 25000000, 'Beta': 1.06, 'PE_Ratio': 25.8, 'Year_Founded': 1998, 'CEO': 'Sundar Pichai'},
    {'Ticker': 'META', 'Name': 'Meta Platforms Inc.', 'Stock_Price': 474.99, 'Sector': 'Technology', 'Market_Cap': 1.2e12, 'Volume': 14000000, 'Beta': 1.21, 'PE_Ratio': 27.3, 'Year_Founded': 2004, 'CEO': 'Mark Zuckerberg'},
    {'Ticker': 'NVDA', 'Name': 'NVIDIA Corporation', 'Stock_Price': 878.37, 'Sector': 'Technology', 'Market_Cap': 2.16e12, 'Volume': 42000000, 'Beta': 1.68, 'PE_Ratio': 68.5, 'Year_Founded': 1993, 'CEO': 'Jensen Huang'},
    {'Ticker': 'TSLA', 'Name': 'Tesla Inc.', 'Stock_Price': 248.50, 'Sector': 'Automotive', 'Market_Cap': 788e9, 'Volume': 95000000, 'Beta': 2.34, 'PE_Ratio': 78.9, 'Year_Founded': 2003, 'CEO': 'Elon Musk'},
    {'Ticker': 'AVGO', 'Name': 'Broadcom Inc.', 'Stock_Price': 1682.50, 'Sector': 'Technology', 'Market_Cap': 785e9, 'Volume': 2100000, 'Beta': 1.08, 'PE_Ratio': 158.3, 'Year_Founded': 1961, 'CEO': 'Hock Tan'},
    {'Ticker': 'ORCL', 'Name': 'Oracle Corporation', 'Stock_Price': 127.35, 'Sector': 'Technology', 'Market_Cap': 349e9, 'Volume': 6800000, 'Beta': 0.89, 'PE_Ratio': 34.2, 'Year_Founded': 1977, 'CEO': 'Safra Catz'},
    {'Ticker': 'ADBE', 'Name': 'Adobe Inc.', 'Stock_Price': 561.23, 'Sector': 'Technology', 'Market_Cap': 251e9, 'Volume': 2300000, 'Beta': 1.15, 'PE_Ratio': 48.7, 'Year_Founded': 1982, 'CEO': 'Shantanu Narayen'},
    {'Ticker': 'CRM', 'Name': 'Salesforce Inc.', 'Stock_Price': 264.73, 'Sector': 'Technology', 'Market_Cap': 258e9, 'Volume': 5400000, 'Beta': 1.12, 'PE_Ratio': 42.1, 'Year_Founded': 1999, 'CEO': 'Marc Benioff'},

    # Financial Services
    {'Ticker': 'BRK.B', 'Name': 'Berkshire Hathaway Inc.', 'Stock_Price': 412.50, 'Sector': 'Financial Services', 'Market_Cap': 896e9, 'Volume': 3200000, 'Beta': 0.89, 'PE_Ratio': 9.8, 'Year_Founded': 1839, 'CEO': 'Warren Buffett'},
    {'Ticker': 'JPM', 'Name': 'JPMorgan Chase & Co.', 'Stock_Price': 189.45, 'Sector': 'Financial Services', 'Market_Cap': 547e9, 'Volume': 9800000, 'Beta': 1.15, 'PE_Ratio': 11.2, 'Year_Founded': 1799, 'CEO': 'Jamie Dimon'},
    {'Ticker': 'V', 'Name': 'Visa Inc.', 'Stock_Price': 274.32, 'Sector': 'Financial Services', 'Market_Cap': 566e9, 'Volume': 6200000, 'Beta': 0.98, 'PE_Ratio': 31.5, 'Year_Founded': 1958, 'CEO': 'Ryan McInerney'},
    {'Ticker': 'MA', 'Name': 'Mastercard Inc.', 'Stock_Price': 461.28, 'Sector': 'Financial Services', 'Market_Cap': 434e9, 'Volume': 2800000, 'Beta': 1.04, 'PE_Ratio': 35.8, 'Year_Founded': 1966, 'CEO': 'Michael Miebach'},
    {'Ticker': 'BAC', 'Name': 'Bank of America Corp', 'Stock_Price': 38.92, 'Sector': 'Financial Services', 'Market_Cap': 303e9, 'Volume': 42000000, 'Beta': 1.35, 'PE_Ratio': 12.4, 'Year_Founded': 1784, 'CEO': 'Brian Moynihan'},
    {'Ticker': 'WFC', 'Name': 'Wells Fargo & Company', 'Stock_Price': 57.84, 'Sector': 'Financial Services', 'Market_Cap': 208e9, 'Volume': 15000000, 'Beta': 1.18, 'PE_Ratio': 11.8, 'Year_Founded': 1852, 'CEO': 'Charles Scharf'},
    {'Ticker': 'GS', 'Name': 'Goldman Sachs Group Inc.', 'Stock_Price': 456.78, 'Sector': 'Financial Services', 'Market_Cap': 152e9, 'Volume': 2100000, 'Beta': 1.42, 'PE_Ratio': 13.5, 'Year_Founded': 1869, 'CEO': 'David Solomon'},
    {'Ticker': 'MS', 'Name': 'Morgan Stanley', 'Stock_Price': 98.45, 'Sector': 'Financial Services', 'Market_Cap': 162e9, 'Volume': 7800000, 'Beta': 1.38, 'PE_Ratio': 14.2, 'Year_Founded': 1935, 'CEO': 'James Gorman'},
    {'Ticker': 'BLK', 'Name': 'BlackRock Inc.', 'Stock_Price': 823.67, 'Sector': 'Financial Services', 'Market_Cap': 123e9, 'Volume': 520000, 'Beta': 1.24, 'PE_Ratio': 22.7, 'Year_Founded': 1988, 'CEO': 'Larry Fink'},
    {'Ticker': 'SCHW', 'Name': 'Charles Schwab Corporation', 'Stock_Price': 68.92, 'Sector': 'Financial Services', 'Market_Cap': 126e9, 'Volume': 6900000, 'Beta': 1.08, 'PE_Ratio': 25.3, 'Year_Founded': 1971, 'CEO': 'Walt Bettinger'},

    # Healthcare
    {'Ticker': 'UNH', 'Name': 'UnitedHealth Group Inc.', 'Stock_Price': 524.67, 'Sector': 'Healthcare', 'Market_Cap': 489e9, 'Volume': 2800000, 'Beta': 0.73, 'PE_Ratio': 28.4, 'Year_Founded': 1977, 'CEO': 'Andrew Witty'},
    {'Ticker': 'JNJ', 'Name': 'Johnson & Johnson', 'Stock_Price': 156.89, 'Sector': 'Healthcare', 'Market_Cap': 377e9, 'Volume': 6500000, 'Beta': 0.55, 'PE_Ratio': 24.2, 'Year_Founded': 1886, 'CEO': 'Joaquin Duato'},
    {'Ticker': 'LLY', 'Name': 'Eli Lilly and Company', 'Stock_Price': 789.34, 'Sector': 'Healthcare', 'Market_Cap': 749e9, 'Volume': 2900000, 'Beta': 0.68, 'PE_Ratio': 117.8, 'Year_Founded': 1876, 'CEO': 'David Ricks'},
    {'Ticker': 'ABBV', 'Name': 'AbbVie Inc.', 'Stock_Price': 167.23, 'Sector': 'Healthcare', 'Market_Cap': 295e9, 'Volume': 5200000, 'Beta': 0.61, 'PE_Ratio': 38.9, 'Year_Founded': 2013, 'CEO': 'Richard Gonzalez'},
    {'Ticker': 'MRK', 'Name': 'Merck & Co. Inc.', 'Stock_Price': 108.45, 'Sector': 'Healthcare', 'Market_Cap': 274e9, 'Volume': 8900000, 'Beta': 0.52, 'PE_Ratio': 16.8, 'Year_Founded': 1891, 'CEO': 'Robert Davis'},
    {'Ticker': 'TMO', 'Name': 'Thermo Fisher Scientific Inc.', 'Stock_Price': 567.89, 'Sector': 'Healthcare', 'Market_Cap': 220e9, 'Volume': 1200000, 'Beta': 0.78, 'PE_Ratio': 35.6, 'Year_Founded': 1956, 'CEO': 'Marc Casper'},
    {'Ticker': 'ABT', 'Name': 'Abbott Laboratories', 'Stock_Price': 112.34, 'Sector': 'Healthcare', 'Market_Cap': 194e9, 'Volume': 4800000, 'Beta': 0.69, 'PE_Ratio': 31.2, 'Year_Founded': 1888, 'CEO': 'Robert Ford'},
    {'Ticker': 'PFE', 'Name': 'Pfizer Inc.', 'Stock_Price': 28.67, 'Sector': 'Healthcare', 'Market_Cap': 161e9, 'Volume': 38000000, 'Beta': 0.64, 'PE_Ratio': 9.4, 'Year_Founded': 1849, 'CEO': 'Albert Bourla'},
    {'Ticker': 'DHR', 'Name': 'Danaher Corporation', 'Stock_Price': 234.56, 'Sector': 'Healthcare', 'Market_Cap': 172e9, 'Volume': 2600000, 'Beta': 0.92, 'PE_Ratio': 38.7, 'Year_Founded': 1984, 'CEO': 'Rainer Blair'},
    {'Ticker': 'CVS', 'Name': 'CVS Health Corporation', 'Stock_Price': 74.23, 'Sector': 'Healthcare', 'Market_Cap': 95e9, 'Volume': 6700000, 'Beta': 0.71, 'PE_Ratio': 11.6, 'Year_Founded': 1963, 'CEO': 'Karen Lynch'},

    # Consumer Discretionary
    {'Ticker': 'AMZN', 'Name': 'Amazon.com Inc.', 'Stock_Price': 178.35, 'Sector': 'Consumer Discretionary', 'Market_Cap': 1.85e12, 'Volume': 48000000, 'Beta': 1.15, 'PE_Ratio': 67.4, 'Year_Founded': 1994, 'CEO': 'Andy Jassy'},
    {'Ticker': 'HD', 'Name': 'Home Depot Inc.', 'Stock_Price': 358.92, 'Sector': 'Consumer Discretionary', 'Market_Cap': 361e9, 'Volume': 3200000, 'Beta': 0.98, 'PE_Ratio': 24.8, 'Year_Founded': 1978, 'CEO': 'Ted Decker'},
    {'Ticker': 'MCD', 'Name': "McDonald's Corporation", 'Stock_Price': 289.45, 'Sector': 'Consumer Discretionary', 'Market_Cap': 209e9, 'Volume': 2600000, 'Beta': 0.63, 'PE_Ratio': 24.3, 'Year_Founded': 1940, 'CEO': 'Chris Kempczinski'},
    {'Ticker': 'NKE', 'Name': 'Nike Inc.', 'Stock_Price': 98.76, 'Sector': 'Consumer Discretionary', 'Market_Cap': 151e9, 'Volume': 8900000, 'Beta': 1.02, 'PE_Ratio': 28.9, 'Year_Founded': 1964, 'CEO': 'John Donahoe'},
    {'Ticker': 'SBUX', 'Name': 'Starbucks Corporation', 'Stock_Price': 95.34, 'Sector': 'Consumer Discretionary', 'Market_Cap': 109e9, 'Volume': 7200000, 'Beta': 0.89, 'PE_Ratio': 26.7, 'Year_Founded': 1971, 'CEO': 'Laxman Narasimhan'},
    {'Ticker': 'TGT', 'Name': 'Target Corporation', 'Stock_Price': 147.82, 'Sector': 'Consumer Discretionary', 'Market_Cap': 68e9, 'Volume': 3800000, 'Beta': 1.08, 'PE_Ratio': 17.4, 'Year_Founded': 1902, 'CEO': 'Brian Cornell'},
    {'Ticker': 'LOW', 'Name': "Lowe's Companies Inc.", 'Stock_Price': 234.67, 'Sector': 'Consumer Discretionary', 'Market_Cap': 142e9, 'Volume': 3100000, 'Beta': 1.12, 'PE_Ratio': 20.8, 'Year_Founded': 1921, 'CEO': 'Marvin Ellison'},
    {'Ticker': 'BKNG', 'Name': 'Booking Holdings Inc.', 'Stock_Price': 3567.89, 'Sector': 'Consumer Discretionary', 'Market_Cap': 131e9, 'Volume': 340000, 'Beta': 1.24, 'PE_Ratio': 28.5, 'Year_Founded': 1996, 'CEO': 'Glenn Fogel'},
    {'Ticker': 'TJX', 'Name': 'TJX Companies Inc.', 'Stock_Price': 98.45, 'Sector': 'Consumer Discretionary', 'Market_Cap': 113e9, 'Volume': 5600000, 'Beta': 0.94, 'PE_Ratio': 27.3, 'Year_Founded': 1956, 'CEO': 'Ernie Herrman'},
    {'Ticker': 'ABNB', 'Name': 'Airbnb Inc.', 'Stock_Price': 138.92, 'Sector': 'Consumer Discretionary', 'Market_Cap': 88e9, 'Volume': 5200000, 'Beta': 1.35, 'PE_Ratio': 42.6, 'Year_Founded': 2008, 'CEO': 'Brian Chesky'},

    # Communication Services
    {'Ticker': 'NFLX', 'Name': 'Netflix Inc.', 'Stock_Price': 612.34, 'Sector': 'Communication Services', 'Market_Cap': 262e9, 'Volume': 3700000, 'Beta': 1.28, 'PE_Ratio': 48.9, 'Year_Founded': 1997, 'CEO': 'Reed Hastings'},
    {'Ticker': 'DIS', 'Name': 'Walt Disney Company', 'Stock_Price': 112.45, 'Sector': 'Communication Services', 'Market_Cap': 205e9, 'Volume': 9400000, 'Beta': 1.18, 'PE_Ratio': 56.2, 'Year_Founded': 1923, 'CEO': 'Bob Iger'},
    {'Ticker': 'CMCSA', 'Name': 'Comcast Corporation', 'Stock_Price': 43.67, 'Sector': 'Communication Services', 'Market_Cap': 176e9, 'Volume': 18000000, 'Beta': 0.97, 'PE_Ratio': 11.3, 'Year_Founded': 1963, 'CEO': 'Brian Roberts'},
    {'Ticker': 'T', 'Name': 'AT&T Inc.', 'Stock_Price': 21.89, 'Sector': 'Communication Services', 'Market_Cap': 156e9, 'Volume': 32000000, 'Beta': 0.67, 'PE_Ratio': 8.7, 'Year_Founded': 1983, 'CEO': 'John Stankey'},
    {'Ticker': 'VZ', 'Name': 'Verizon Communications Inc.', 'Stock_Price': 42.34, 'Sector': 'Communication Services', 'Market_Cap': 178e9, 'Volume': 15000000, 'Beta': 0.45, 'PE_Ratio': 9.2, 'Year_Founded': 1983, 'CEO': 'Hans Vestberg'},

    # Energy
    {'Ticker': 'XOM', 'Name': 'Exxon Mobil Corporation', 'Stock_Price': 112.67, 'Sector': 'Energy', 'Market_Cap': 462e9, 'Volume': 16000000, 'Beta': 0.92, 'PE_Ratio': 12.3, 'Year_Founded': 1999, 'CEO': 'Darren Woods'},
    {'Ticker': 'CVX', 'Name': 'Chevron Corporation', 'Stock_Price': 158.23, 'Sector': 'Energy', 'Market_Cap': 294e9, 'Volume': 7800000, 'Beta': 0.88, 'PE_Ratio': 10.8, 'Year_Founded': 1879, 'CEO': 'Mike Wirth'},
    {'Ticker': 'COP', 'Name': 'ConocoPhillips', 'Stock_Price': 117.45, 'Sector': 'Energy', 'Market_Cap': 148e9, 'Volume': 6200000, 'Beta': 1.23, 'PE_Ratio': 11.7, 'Year_Founded': 1917, 'CEO': 'Ryan Lance'},
    {'Ticker': 'SLB', 'Name': 'Schlumberger Limited', 'Stock_Price': 48.92, 'Sector': 'Energy', 'Market_Cap': 69e9, 'Volume': 9800000, 'Beta': 1.45, 'PE_Ratio': 14.6, 'Year_Founded': 1926, 'CEO': 'Olivier Le Peuch'},
    {'Ticker': 'EOG', 'Name': 'EOG Resources Inc.', 'Stock_Price': 123.56, 'Sector': 'Energy', 'Market_Cap': 72e9, 'Volume': 3400000, 'Beta': 1.38, 'PE_Ratio': 10.9, 'Year_Founded': 1985, 'CEO': 'Ezra Yacob'},

    # Industrials
    {'Ticker': 'BA', 'Name': 'Boeing Company', 'Stock_Price': 187.45, 'Sector': 'Industrials', 'Market_Cap': 115e9, 'Volume': 6700000, 'Beta': 1.78, 'PE_Ratio': -38.4, 'Year_Founded': 1916, 'CEO': 'Dave Calhoun'},
    {'Ticker': 'HON', 'Name': 'Honeywell International Inc.', 'Stock_Price': 203.67, 'Sector': 'Industrials', 'Market_Cap': 135e9, 'Volume': 2400000, 'Beta': 1.08, 'PE_Ratio': 25.7, 'Year_Founded': 1906, 'CEO': 'Vimal Kapur'},
    {'Ticker': 'UPS', 'Name': 'United Parcel Service Inc.', 'Stock_Price': 148.92, 'Sector': 'Industrials', 'Market_Cap': 129e9, 'Volume': 2900000, 'Beta': 1.02, 'PE_Ratio': 17.8, 'Year_Founded': 1907, 'CEO': 'Carol Tomé'},
    {'Ticker': 'CAT', 'Name': 'Caterpillar Inc.', 'Stock_Price': 312.45, 'Sector': 'Industrials', 'Market_Cap': 161e9, 'Volume': 2600000, 'Beta': 1.15, 'PE_Ratio': 18.3, 'Year_Founded': 1925, 'CEO': 'Jim Umpleby'},
    {'Ticker': 'GE', 'Name': 'General Electric Company', 'Stock_Price': 123.78, 'Sector': 'Industrials', 'Market_Cap': 136e9, 'Volume': 5800000, 'Beta': 1.34, 'PE_Ratio': 24.5, 'Year_Founded': 1892, 'CEO': 'Larry Culp'},
    {'Ticker': 'RTX', 'Name': 'RTX Corporation', 'Stock_Price': 98.67, 'Sector': 'Industrials', 'Market_Cap': 142e9, 'Volume': 4200000, 'Beta': 1.12, 'PE_Ratio': 29.8, 'Year_Founded': 1922, 'CEO': 'Greg Hayes'},
    {'Ticker': 'DE', 'Name': 'Deere & Company', 'Stock_Price': 398.23, 'Sector': 'Industrials', 'Market_Cap': 114e9, 'Volume': 1800000, 'Beta': 1.24, 'PE_Ratio': 13.6, 'Year_Founded': 1837, 'CEO': 'John May'},
    {'Ticker': 'LMT', 'Name': 'Lockheed Martin Corporation', 'Stock_Price': 467.89, 'Sector': 'Industrials', 'Market_Cap': 118e9, 'Volume': 1200000, 'Beta': 0.68, 'PE_Ratio': 18.9, 'Year_Founded': 1912, 'CEO': 'James Taiclet'},
    {'Ticker': 'UNP', 'Name': 'Union Pacific Corporation', 'Stock_Price': 245.67, 'Sector': 'Industrials', 'Market_Cap': 152e9, 'Volume': 2500000, 'Beta': 1.18, 'PE_Ratio': 22.4, 'Year_Founded': 1862, 'CEO': 'Lance Fritz'},
    {'Ticker': 'MMM', 'Name': '3M Company', 'Stock_Price': 98.45, 'Sector': 'Industrials', 'Market_Cap': 55e9, 'Volume': 4100000, 'Beta': 0.98, 'PE_Ratio': 15.7, 'Year_Founded': 1902, 'CEO': 'Mike Roman'},

    # Consumer Staples
    {'Ticker': 'WMT', 'Name': 'Walmart Inc.', 'Stock_Price': 167.89, 'Sector': 'Consumer Staples', 'Market_Cap': 452e9, 'Volume': 7200000, 'Beta': 0.52, 'PE_Ratio': 28.4, 'Year_Founded': 1962, 'CEO': 'Doug McMillon'},
    {'Ticker': 'PG', 'Name': 'Procter & Gamble Company', 'Stock_Price': 156.78, 'Sector': 'Consumer Staples', 'Market_Cap': 374e9, 'Volume': 6400000, 'Beta': 0.41, 'PE_Ratio': 25.6, 'Year_Founded': 1837, 'CEO': 'Jon Moeller'},
    {'Ticker': 'KO', 'Name': 'Coca-Cola Company', 'Stock_Price': 61.23, 'Sector': 'Consumer Staples', 'Market_Cap': 264e9, 'Volume': 13000000, 'Beta': 0.57, 'PE_Ratio': 26.8, 'Year_Founded': 1892, 'CEO': 'James Quincey'},
    {'Ticker': 'PEP', 'Name': 'PepsiCo Inc.', 'Stock_Price': 178.45, 'Sector': 'Consumer Staples', 'Market_Cap': 246e9, 'Volume': 4200000, 'Beta': 0.63, 'PE_Ratio': 28.3, 'Year_Founded': 1898, 'CEO': 'Ramon Laguarta'},
    {'Ticker': 'COST', 'Name': 'Costco Wholesale Corporation', 'Stock_Price': 734.56, 'Sector': 'Consumer Staples', 'Market_Cap': 326e9, 'Volume': 1900000, 'Beta': 0.72, 'PE_Ratio': 45.7, 'Year_Founded': 1976, 'CEO': 'Ron Vachris'},
    {'Ticker': 'PM', 'Name': 'Philip Morris International Inc.', 'Stock_Price': 98.67, 'Sector': 'Consumer Staples', 'Market_Cap': 153e9, 'Volume': 4800000, 'Beta': 0.64, 'PE_Ratio': 18.9, 'Year_Founded': 2008, 'CEO': 'Jacek Olczak'},
    {'Ticker': 'MO', 'Name': 'Altria Group Inc.', 'Stock_Price': 48.92, 'Sector': 'Consumer Staples', 'Market_Cap': 87e9, 'Volume': 7600000, 'Beta': 0.58, 'PE_Ratio': 9.4, 'Year_Founded': 1985, 'CEO': 'Billy Gifford'},
    {'Ticker': 'MDLZ', 'Name': 'Mondelez International Inc.', 'Stock_Price': 72.34, 'Sector': 'Consumer Staples', 'Market_Cap': 98e9, 'Volume': 6200000, 'Beta': 0.68, 'PE_Ratio': 24.1, 'Year_Founded': 2012, 'CEO': 'Dirk Van de Put'},
    {'Ticker': 'CL', 'Name': 'Colgate-Palmolive Company', 'Stock_Price': 87.56, 'Sector': 'Consumer Staples', 'Market_Cap': 72e9, 'Volume': 4100000, 'Beta': 0.53, 'PE_Ratio': 32.8, 'Year_Founded': 1806, 'CEO': 'Noel Wallace'},
    {'Ticker': 'KMB', 'Name': 'Kimberly-Clark Corporation', 'Stock_Price': 134.78, 'Sector': 'Consumer Staples', 'Market_Cap': 45e9, 'Volume': 1800000, 'Beta': 0.47, 'PE_Ratio': 23.6, 'Year_Founded': 1872, 'CEO': 'Mike Hsu'},

    # Materials
    {'Ticker': 'LIN', 'Name': 'Linde plc', 'Stock_Price': 423.45, 'Sector': 'Materials', 'Market_Cap': 209e9, 'Volume': 1600000, 'Beta': 0.84, 'PE_Ratio': 32.7, 'Year_Founded': 1879, 'CEO': 'Sanjiv Lamba'},
    {'Ticker': 'APD', 'Name': 'Air Products and Chemicals Inc.', 'Stock_Price': 287.92, 'Sector': 'Materials', 'Market_Cap': 64e9, 'Volume': 980000, 'Beta': 0.89, 'PE_Ratio': 28.4, 'Year_Founded': 1940, 'CEO': 'Seifi Ghasemi'},
    {'Ticker': 'SHW', 'Name': 'Sherwin-Williams Company', 'Stock_Price': 312.67, 'Sector': 'Materials', 'Market_Cap': 80e9, 'Volume': 1200000, 'Beta': 1.08, 'PE_Ratio': 34.9, 'Year_Founded': 1866, 'CEO': 'Heidi Petz'},
    {'Ticker': 'FCX', 'Name': 'Freeport-McMoRan Inc.', 'Stock_Price': 43.28, 'Sector': 'Materials', 'Market_Cap': 61e9, 'Volume': 14000000, 'Beta': 1.95, 'PE_Ratio': 19.8, 'Year_Founded': 1912, 'CEO': 'Kathleen Quirk'},
    {'Ticker': 'NEM', 'Name': 'Newmont Corporation', 'Stock_Price': 42.56, 'Sector': 'Materials', 'Market_Cap': 33e9, 'Volume': 8900000, 'Beta': 0.54, 'PE_Ratio': 48.3, 'Year_Founded': 1921, 'CEO': 'Tom Palmer'},

    # Utilities
    {'Ticker': 'NEE', 'Name': 'NextEra Energy Inc.', 'Stock_Price': 72.34, 'Sector': 'Utilities', 'Market_Cap': 145e9, 'Volume': 8200000, 'Beta': 0.48, 'PE_Ratio': 23.8, 'Year_Founded': 1925, 'CEO': 'John Ketchum'},
    {'Ticker': 'DUK', 'Name': 'Duke Energy Corporation', 'Stock_Price': 103.45, 'Sector': 'Utilities', 'Market_Cap': 79e9, 'Volume': 2800000, 'Beta': 0.39, 'PE_Ratio': 19.6, 'Year_Founded': 1904, 'CEO': 'Lynn Good'},
    {'Ticker': 'SO', 'Name': 'Southern Company', 'Stock_Price': 78.92, 'Sector': 'Utilities', 'Market_Cap': 86e9, 'Volume': 3600000, 'Beta': 0.52, 'PE_Ratio': 21.4, 'Year_Founded': 1945, 'CEO': 'Chris Womack'},
    {'Ticker': 'D', 'Name': 'Dominion Energy Inc.', 'Stock_Price': 54.67, 'Sector': 'Utilities', 'Market_Cap': 45e9, 'Volume': 3200000, 'Beta': 0.58, 'PE_Ratio': 17.8, 'Year_Founded': 1983, 'CEO': 'Robert Blue'},
    {'Ticker': 'AEP', 'Name': 'American Electric Power Company', 'Stock_Price': 92.34, 'Sector': 'Utilities', 'Market_Cap': 48e9, 'Volume': 2100000, 'Beta': 0.46, 'PE_Ratio': 18.9, 'Year_Founded': 1906, 'CEO': 'Julie Sloat'},

    # Real Estate
    {'Ticker': 'AMT', 'Name': 'American Tower Corporation', 'Stock_Price': 218.45, 'Sector': 'Real Estate', 'Market_Cap': 102e9, 'Volume': 1800000, 'Beta': 0.68, 'PE_Ratio': 56.7, 'Year_Founded': 1995, 'CEO': 'Tom Bartlett'},
    {'Ticker': 'PLD', 'Name': 'Prologis Inc.', 'Stock_Price': 132.78, 'Sector': 'Real Estate', 'Market_Cap': 121e9, 'Volume': 2400000, 'Beta': 0.95, 'PE_Ratio': 48.3, 'Year_Founded': 1983, 'CEO': 'Hamid Moghadam'},
    {'Ticker': 'CCI', 'Name': 'Crown Castle Inc.', 'Stock_Price': 112.34, 'Sector': 'Real Estate', 'Market_Cap': 49e9, 'Volume': 2100000, 'Beta': 0.72, 'PE_Ratio': 42.1, 'Year_Founded': 1994, 'CEO': 'Steven Moskowitz'},
    {'Ticker': 'EQIX', 'Name': 'Equinix Inc.', 'Stock_Price': 867.92, 'Sector': 'Real Estate', 'Market_Cap': 81e9, 'Volume': 320000, 'Beta': 0.89, 'PE_Ratio': 98.7, 'Year_Founded': 1998, 'CEO': 'Charles Meyers'},
    {'Ticker': 'SPG', 'Name': 'Simon Property Group Inc.', 'Stock_Price': 156.45, 'Sector': 'Real Estate', 'Market_Cap': 52e9, 'Volume': 1600000, 'Beta': 1.28, 'PE_Ratio': 21.8, 'Year_Founded': 1960, 'CEO': 'David Simon'},
]

# To create a DataFrame from this list, you can use:
sp500_df = pd.DataFrame(sp500_companies)

In [164]:
sp500_df

,Ticker,Name,Stock_Price,Sector,Market_Cap,Volume,Beta,PE_Ratio,Year_Founded,CEO
0,AAPL,Apple Inc.,178.25,Technology,2.800000e+12,52000000,1.29,29.5,1976,Tim Cook
1,MSFT,Microsoft Corporation,378.91,Technology,2.820000e+12,22000000,0.90,35.2,1975,Satya Nadella
2,GOOGL,Alphabet Inc.,141.80,Technology,1.770000e+12,25000000,1.06,25.8,1998,Sundar Pichai
3,META,Meta Platforms Inc.,474.99,Technology,1.200000e+12,14000000,1.21,27.3,2004,Mark Zuckerberg
4,NVDA,NVIDIA Corporation,878.37,Technology,2.160000e+12,42000000,1.68,68.5,1993,Jensen Huang
...,...,...,...,...,...,...,...,...,...,...
80,AMT,American Tower Corporation,218.45,Real Estate,1.020000e+11,1800000,0.68,56.7,1995,Tom Bartlett
81,PLD,Prologis Inc.,132.78,Real Estate,1.210000e+11,2400000,0.95,48.3,1983,Hamid Moghadam
82,CCI,Crown Castle Inc.,112.34,Real Estate,4.900000e+10,2100000,0.72,42.1,1994,Steven Moskowitz
83,EQIX,Equinix Inc.,867.92,Real Estate,8.100000e+10,320000,0.89,98.7,1998,Charles Meyers
84,SPG,Simon Property Group Inc.,156.45,Real Estate,5.200000e+10,1600000,1.28,21.8,1960,David Simon

In [166]:
sp500_df.groupby('Sector')[['Stock_Price']].mean()

                        Stock_Price
Sector
Automotive               248.500000
Communication Services   166.538000
Consumer Discretionary   520.857000
Consumer Staples         174.118000
Energy                   112.166000
Financial Services       288.213000
Healthcare               276.427000
Industrials              228.518000
Materials                221.976000
Real Estate              297.588000
Technology               520.903333
Utilities                 80.344000